'use strict';
const sb=window.koldisSupabase;
const app=document.getElementById('adminApp');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const date=s=>s?new Date(s).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'}):'—';
function loading(){app.innerHTML='<div class="loading">KOLDIS Admin wird geladen …</div>'}
async function session(){const {data,error}=await sb.auth.getSession();if(error)throw error;return data.session}
async function isAdmin(user){const {data,error}=await sb.from('koldis_admins').select('user_id').eq('user_id',user.id).maybeSingle();if(error)throw error;return !!data}
function login(){app.innerHTML=`<main class="login panel"><div class="eyebrow">KOLDIS INTERN</div><h1>Adminbereich</h1><p class="sub">Nur dein freigeschaltetes KOLDIS-Konto kann diesen Bereich öffnen.</p><div id="msg"></div><form id="f"><label>E-Mail<br><input id="email" type="email" required autocomplete="email" style="width:100%;margin:7px 0 14px;padding:13px;border-radius:11px;border:1px solid var(--line);background:#09110e;color:var(--text)"></label><label>Passwort<br><input id="pw" type="password" required autocomplete="current-password" style="width:100%;margin:7px 0 14px;padding:13px;border-radius:11px;border:1px solid var(--line);background:#09110e;color:var(--text)"></label><button class="btn" style="width:100%">🔐 Admin anmelden</button></form><div class="setup">Wichtig: Die Berechtigung kommt <b>nicht</b> aus dieser Seite, sondern aus Supabase RLS. Dein Konto muss einmal in <code>koldis_admins</code> eingetragen werden.</div></main>`;app.querySelector('#f').onsubmit=async e=>{e.preventDefault();const msg=app.querySelector('#msg');msg.innerHTML='';try{const {error}=await sb.auth.signInWithPassword({email:app.querySelector('#email').value.trim(),password:app.querySelector('#pw').value});if(error)throw error;location.reload()}catch(err){msg.innerHTML=`<div class="notice">${esc(err.message||'Anmeldung fehlgeschlagen.')}</div>`}}}
async function count(table,filter){let q=sb.from(table).select('*',{count:'exact',head:true});if(filter)q=filter(q);const {count,error}=await q;if(error)throw error;return count||0}
async function loadEvents(){const {data,error}=await sb.from('koldis_events').select('event_name,created_at').order('created_at',{ascending:false}).limit(1000);if(error)throw error;const map={};(data||[]).forEach(x=>map[x.event_name]=(map[x.event_name]||0)+1);return Object.entries(map).sort((a,b)=>b[1]-a[1])}
async function loadFeedback(){const {data,error}=await sb.from('koldis_feedback').select('id,rating,category,message,status,created_at,user_id').order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[]}
async function setFeedbackStatus(id,status){const {error}=await sb.from('koldis_feedback').update({status}).eq('id',id);if(error)throw error;render()}
async function render(){loading();try{const s=await session();if(!s){login();return}if(!(await isAdmin(s.user))){app.innerHTML=`<main class="login panel"><div class="eyebrow">KOLDIS INTERN</div><h1>Kein Zugriff.</h1><p class="sub">Dieses Konto ist nicht als KOLDIS-Administrator freigeschaltet.</p><button class="btn" id="logout">Abmelden</button></main>`;app.querySelector('#logout').onclick=async()=>{await sb.auth.signOut();render()};return}
const [users,eventsCount,feedbackCount,events,feedback]=await Promise.all([count('profiles'),count('koldis_events'),count('koldis_feedback'),loadEvents(),loadFeedback()]);
app.innerHTML=`<div class="wrap"><header class="top"><div><div class="eyebrow">KOLDIS INTERN</div><div class="brand">📊 Admin Dashboard</div><div class="sub">Nutzung, Feedback und Produktentwicklung auf einen Blick.</div></div><button class="btn danger" id="logout">🚪 Abmelden</button></header><div class="grid"><div class="stat"><small>REGISTRIERTE NUTZER</small><strong>${users}</strong></div><div class="stat"><small>TRACKING-EVENTS</small><strong>${eventsCount}</strong></div><div class="stat"><small>FEEDBACK</small><strong>${feedbackCount}</strong></div><div class="stat"><small>NEUES FEEDBACK</small><strong>${feedback.filter(x=>x.status==='new'||!x.status).length}</strong></div></div><section class="section"><h2>📈 Welche Funktionen werden benutzt?</h2><div class="panel"><div class="events">${events.length?events.map(([name,n])=>`<div class="event"><div class="name">${esc(name)}</div><div class="num">${n}</div></div>`).join(''):'<div class="sub">Noch keine Nutzungsdaten vorhanden. Sobald KOLDIS Events sendet, erscheinen sie hier.</div>'}</div></div></section><section class="section"><h2>💬 Kundenfeedback</h2><div class="panel"><div class="feedback">${feedback.length?feedback.map(x=>`<article class="feedback-item"><div class="feedback-head"><div><span class="rating">${'★'.repeat(Math.max(0,Math.min(5,Number(x.rating)||0)))}${'☆'.repeat(5-Math.max(0,Math.min(5,Number(x.rating)||0)))}</span> <span class="category">${esc(x.category||'Sonstiges')}</span></div><span class="status ${x.status==='new'||!x.status?'new':''}">${esc(x.status||'new')}</span></div><div class="message">${esc(x.message)}</div><div class="meta">${date(x.created_at)} · ${x.user_id?'angemeldet':'Gast'}</div><div class="row-actions"><button class="btn" data-status="read" data-id="${esc(x.id)}">✓ Als gelesen</button><button class="btn" data-status="done" data-id="${esc(x.id)}">✓ Erledigt</button></div></article>`).join(''):'<div class="sub">Noch kein Feedback.</div>'}</div></div></section><section class="section"><h2>🔒 Sicherheit</h2><div class="panel"><div class="sub">Der Adminbereich zeigt Daten nur nach erfolgreicher Supabase-Anmeldung und erfolgreicher Prüfung in <code>koldis_admins</code>. Es wird kein Service-Role-Key im Browser verwendet.</div></div></section></div>`;
app.querySelector('#logout').onclick=async()=>{await sb.auth.signOut();render()};app.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await setFeedbackStatus(b.dataset.id,b.dataset.status)}catch(e){alert(e.message)}finally{b.disabled=false}})
}catch(e){app.innerHTML=`<main class="login panel"><h1>Admin konnte nicht geladen werden.</h1><div class="notice">${esc(e.message||e)}</div><button class="btn" id="retry">Erneut versuchen</button></main>`;app.querySelector('#retry').onclick=render}}
render();
